### ISSUE TITLE
could not replicate the sample code of TreeWASDir

### ISSUE THREAD

**Issue by jielab** [mcveanlab/TreeWASDir#3]
Hi, there:

Can someone please let me know the difference between TreeWAS and TreeWASDir? It seems that the former is not updated for a long while. 

I am trying to follow the example code in TreeWASDir github page. However, I got the following error.

<img width="316" alt="1" src="https://user-images.githubusercontent.com/26947455/103289823-1b769880-4a23-11eb-9c91-312626ae0233.png">

<img width="531" alt="2" src="https://user-images.githubusercontent.com/26947455/103289838-22051000-4a23-11eb-9aa9-0b2f5ca7fb9b.png">

Can someone please let me know how to fix this?

Thank you & Best regards,
Jie

**Comment by ac257** [comment]
looks like you haven't installed the dependencies. are you able to load Rgraphviz and graph?

**Comment by jielab** [comment]
Thank you very much!

The error message is now gone, after I loaded library(Rgraphviz) in R.
However, there is no plot in the output, but only some text as shown below.
![11](https://user-images.githubusercontent.com/26947455/103352741-0ca2eb00-4ae2-11eb-84b7-1c09806cf091.jpg)


As I asked in my original email, can you please let me know the difference between TreeWAS and TreeWASDir? What does "Dir" here mean? It seems that the github page for TreeWAS has not been updated for a long while. Is it retired?

Best regards,
Jie
